name: Docker Image Delivery

on:
  workflow_dispatch:

jobs:
  deliver:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Set Image Tag
        id: image-tag
        run: echo "TAG=$(date +%s)-ci" >> "$GITHUB_OUTPUT"
      - name: Build the Docker image
        env:
          TAG: ${{ steps.image-tag.outputs.TAG }}
        run: docker build --file Dockerfile --tag "ziromark/docker:$TAG" .
      - name: login to docker hub
#        run: echo "password" | docker login -u ziromark --password-stdin
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push the Docker Images
        env:
          TAG: ${{ steps.image-tag.outputs.TAG }}
        run: docker push "${{ secrets.DOCKERHUB_USERNAME }}/docker:$TAG"
      - name: Tag Image as latest
        env:
          TAG: ${{ steps.image-tag.outputs.TAG }}
        run:
          docker tag "${{ secrets.DOCKERHUB_USERNAME }}/docker:$TAG" \
            "${{ secrets.DOCKERHUB_USERNAME }}/docker:latest"
      - name: Push latest
        run: docker push "${{ secrets.DOCKERHUB_USERNAME }}/docker:latest"